import Dexie, { type Table } from 'dexie';

export interface Folder {
  id?: number;
  syncId: string;
  name: string;
  parentId?: number;
  color?: string;
  createdAt: number;
  updatedAt: number;
  deletedAt?: number;
}

export type NoteType = 'text' | 'handwriting';

export interface Note {
  id?: number;
  syncId: string;
  title: string;
  content: string;
  folderId?: number;
  color?: string;
  createdAt: number;
  updatedAt: number;
  type?: NoteType;
  deletedAt?: number;
}

export function newSyncId(): string {
  if (typeof crypto !== 'undefined' && typeof crypto.randomUUID === 'function') {
    return crypto.randomUUID();
  }
  // Fallback (very unlikely on modern browsers)
  return 'sid-' + Math.random().toString(36).slice(2) + Date.now().toString(36);
}

export interface HandwritingStroke {
  points: { x: number; y: number }[];
  color: string;
  width: number;
}

export interface HandwritingDoc {
  strokes: HandwritingStroke[];
  width: number;
  height: number;
}

export const EMPTY_HANDWRITING: HandwritingDoc = { strokes: [], width: 1280, height: 1800 };

export function parseHandwriting(content: string): HandwritingDoc {
  if (!content) return { ...EMPTY_HANDWRITING };
  try {
    const data = JSON.parse(content) as Partial<HandwritingDoc>;
    return {
      strokes: Array.isArray(data.strokes) ? data.strokes : [],
      width: typeof data.width === 'number' ? data.width : EMPTY_HANDWRITING.width,
      height: typeof data.height === 'number' ? data.height : EMPTY_HANDWRITING.height,
    };
  } catch {
    return { ...EMPTY_HANDWRITING };
  }
}

export function serializeHandwriting(doc: HandwritingDoc): string {
  return JSON.stringify(doc);
}

export interface ImageAsset {
  id?: number;
  noteId: number;
  blob: Blob;
  type: string;
}

// A saved lily / sikunlily conversation. `messages` is a JSON-serialized
// ChatMessage[] (heavy attachment data stripped before saving).
export interface SavedChat {
  id?: number;
  title: string;
  model: 'lily' | 'sikunlily';
  messages: string;
  count: number;
  createdAt: number;
  updatedAt?: number;  // version clock — bumped on mutation incl. soft-delete
  deletedAt?: number;  // tombstone for sync; UI filters these out
}

export interface Exam {
  id?: number;
  name: string;
  examDate: string;  // YYYY-MM-DD
  createdAt: number;
}

export interface ScheduleDay {
  id?: number;
  date: string;        // YYYY-MM-DD
  tasks: string;       // JSON: string[]
  completed: boolean;
  skipped: boolean;
  createdAt: number;
}

export interface StudyCategory {
  id?: number;
  name: string;
  color: string;
  createdAt: number;
  syncId?: string;     // stable cross-device id for sync
  updatedAt?: number;  // version clock — bumped on every mutation incl. delete
  deletedAt?: number;  // tombstone for sync; UI filters these out
}

export interface StudySession {
  id?: number;
  date: string;
  startTime: number;
  endTime: number;
  duration: number;      // seconds
  categoryId: number | null;
  categoryName: string | null;
  categoryColor: string | null;
  source: 'stopwatch' | 'pomodoro';
  syncId?: string;     // stable cross-device id for sync
  updatedAt?: number;  // version clock — bumped on every mutation incl. delete
  deletedAt?: number;  // tombstone for sync; UI filters these out
}

// A badge the user has unlocked. badgeId matches a BadgeDef.id in lib/badges.ts.
export interface EarnedBadge {
  badgeId: string;
  earnedAt: number;
}

export interface Todo {
  id?: number;
  text: string;
  done: boolean;
  pinned: boolean;
  createdAt: number;
  updatedAt?: number;  // bumped on every mutation — drives last-write-wins sync
  deletedAt?: number;  // tombstone for sync — UI filters these out
  dueDate?: string;    // 'YYYY-MM-DD' — optional scheduled date (予定表 calendar)
  startTime?: string;  // optional 'HH:MM' time-of-day for the scheduled date
}

export interface AlbumPhoto {
  id?: number;
  blob: Blob;
  mimeType: string;
  createdAt: number;
}

// A reference document attached to a skill: extracted plain text from a PDF,
// a fetched URL, or pasted text. We store the extracted text (not the binary)
// so it can be injected straight into the system prompt.
export interface SkillReference {
  type: 'pdf' | 'url' | 'text';
  name: string;   // file name, URL, or a short label
  content: string; // extracted plain text
}

// A user-authored (or sample) "skill" — like a Claude skill: a system-prompt
// instruction plus optional reference materials that change how Lily behaves
// for the whole conversation while the skill is active.
export interface Skill {
  id?: number;
  emoji: string;
  name: string;
  instructions: string;
  references: SkillReference[];
  builtinKey?: string; // set for seeded samples so we don't re-seed them
  createdAt: number;
  updatedAt: number;
}

// ── Practice / 演習 ────────────────────────────────────────────────────────────
// A self-contained problem set generated by Lily and solved in a dedicated
// full-screen view (NOT embedded in a memo). Unlike the in-memo QA block, these
// support long reading passages, charts, multiple-choice, written and
// true/false questions — the full range of real exam questions.
export type PracticeQType = 'mcq' | 'written' | 'fill' | 'tf';

export interface PracticeQuestion {
  id: string;
  type: PracticeQType;
  passage?: string;      // shared long-form reading/context (markdown + latex)
  prompt: string;        // the question itself (markdown + latex)
  chart?: string;        // optional Chart.js config as JSON (graph questions)
  choices?: string[];    // mcq: the options
  correct?: number;      // mcq: index of correct option / tf: 0=○(true) 1=×(false)
  answer?: string;       // written / fill: the model answer
  explanation?: string;  // shown after answering
  points?: number;       // exam mode: marks allocated to this question
}

export interface ProblemSet {
  id?: number;
  title: string;
  subject?: string;
  questions: PracticeQuestion[];
  count: number;
  examMode?: boolean;    // a timed, points-based mock exam (vs casual practice)
  timeLimitSec?: number; // exam mode: countdown length in seconds
  createdAt: number;
  bestScore?: number;    // best correct-count across attempts
  attempts?: number;     // how many times solved
  updatedAt?: number;    // version clock — bumped on mutation incl. soft-delete
  deletedAt?: number;    // tombstone for sync; UI filters these out
}

export class LilyDatabase extends Dexie {
  folders!: Table<Folder>;
  notes!: Table<Note>;
  images!: Table<ImageAsset>;
  savedChats!: Table<SavedChat>;
  exams!: Table<Exam>;
  scheduleDays!: Table<ScheduleDay>;
  studyCategories!: Table<StudyCategory>;
  studySessions!: Table<StudySession>;
  todos!: Table<Todo>;
  albumPhotos!: Table<AlbumPhoto>;
  earnedBadges!: Table<EarnedBadge, string>;
  skills!: Table<Skill>;
  problemSets!: Table<ProblemSet>;

  constructor() {
    super('LilyDatabase');
    this.version(1).stores({
      folders: '++id, name, parentId, color, createdAt',
      notes: '++id, title, folderId, color, createdAt, updatedAt',
      images: '++id, noteId, type'
    });
    this.version(2).stores({
      notes: '++id, title, folderId, color, createdAt, updatedAt, syncCode'
    });
    this.version(3).stores({
      notes: '++id, title, folderId, color, createdAt, updatedAt, syncCode, serverId',
      folders: '++id, name, parentId, color, createdAt, serverId',
    });
    this.version(4).stores({
      notes: '++id, syncId, title, folderId, color, createdAt, updatedAt, syncCode, serverId',
    });
    this.version(5).stores({
      notes: '++id, title, folderId, color, createdAt, updatedAt',
      folders: '++id, name, parentId, color, createdAt',
    });
    this.version(6).stores({
      notes: '++id, title, folderId, color, createdAt, updatedAt, type',
      folders: '++id, name, parentId, color, createdAt',
    });
    this.version(7).stores({
      notes: '++id, syncId, title, folderId, color, createdAt, updatedAt, type, deletedAt',
      folders: '++id, syncId, name, parentId, color, createdAt, updatedAt, deletedAt',
    }).upgrade(async tx => {
      const now = Date.now();
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      await tx.table('folders').toCollection().modify((f: any) => {
        if (!f.syncId) f.syncId = newSyncId();
        if (!f.updatedAt) f.updatedAt = f.createdAt ?? now;
      });
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      await tx.table('notes').toCollection().modify((n: any) => {
        if (!n.syncId) n.syncId = newSyncId();
      });
    });
    this.version(8).stores({
      savedChats: '++id, model, createdAt',
    });
    this.version(9).stores({
      exams: '++id, name, examDate, createdAt',
      scheduleDays: '++id, date, completed, skipped, createdAt',
    });
    this.version(10).stores({
      studyCategories: '++id, name, color, createdAt',
      studySessions: '++id, date, startTime, categoryId',
    });
    this.version(11).stores({
      todos: '++id, done, pinned, createdAt',
    });
    this.version(12).stores({
      albumPhotos: '++id, createdAt',
    });
    this.version(13).stores({
      todos: '++id, done, pinned, createdAt, deletedAt',
    });
    this.version(14).stores({
      todos: '++id, done, pinned, createdAt, updatedAt, deletedAt',
    }).upgrade(async tx => {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      await tx.table('todos').toCollection().modify((t: any) => {
        if (!t.updatedAt) t.updatedAt = t.deletedAt ?? t.createdAt ?? Date.now();
      });
    });
    this.version(15).stores({
      earnedBadges: '&badgeId, earnedAt',
    });
    this.version(16).stores({
      studyCategories: '++id, syncId, name, color, createdAt, updatedAt, deletedAt',
      studySessions: '++id, syncId, date, startTime, categoryId, updatedAt, deletedAt',
    }).upgrade(async tx => {
      // Derive syncId deterministically from stable content so the SAME row on
      // two devices gets the SAME id (a random id per device would make every
      // existing session/category look unique and never reconcile/delete).
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      await tx.table('studyCategories').toCollection().modify((c: any) => {
        if (!c.syncId) c.syncId = `c_${c.name}`;
        if (!c.updatedAt) c.updatedAt = c.createdAt ?? Date.now();
      });
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      await tx.table('studySessions').toCollection().modify((s: any) => {
        if (!s.syncId) s.syncId = `s_${s.date}_${s.startTime}`;
        if (!s.updatedAt) s.updatedAt = s.startTime ?? Date.now();
      });
    });
    this.version(17).stores({
      skills: '++id, name, builtinKey, createdAt',
    });
    this.version(18).stores({
      problemSets: '++id, title, subject, createdAt',
    });
    // v19: give savedChats & problemSets a version clock + tombstone so their
    // deletions sync (previously add-only union). Todos gain a dueDate index so
    // the 予定表 (calendar) view can query by scheduled day.
    this.version(19).stores({
      todos: '++id, done, pinned, createdAt, updatedAt, deletedAt, dueDate',
      savedChats: '++id, model, createdAt, updatedAt, deletedAt',
      problemSets: '++id, title, subject, createdAt, updatedAt, deletedAt',
    }).upgrade(async tx => {
      const now = Date.now();
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      await tx.table('savedChats').toCollection().modify((c: any) => {
        if (!c.updatedAt) c.updatedAt = c.createdAt ?? now;
      });
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      await tx.table('problemSets').toCollection().modify((p: any) => {
        if (!p.updatedAt) p.updatedAt = p.createdAt ?? now;
      });
    });
  }
}

export const db = new LilyDatabase();

// Soft-delete helpers. We set a `deletedAt` tombstone (and bump `updatedAt`)
// instead of removing the row, so the deletion propagates through liveSync /
// backup — a hard delete just makes the row vanish locally and the other
// device, which only ever adds/updates from the remote snapshot, would keep it.
export async function softDeleteNote(id: number): Promise<void> {
  const t = Date.now();
  await db.notes.update(id, { deletedAt: t, updatedAt: t });
}

export async function softDeleteNotes(ids: number[]): Promise<void> {
  const t = Date.now();
  await Promise.all(ids.map(id => db.notes.update(id, { deletedAt: t, updatedAt: t })));
}

export async function softDeleteFolder(id: number): Promise<void> {
  const t = Date.now();
  await db.folders.update(id, { deletedAt: t, updatedAt: t });
}

export async function softDeleteSession(id: number): Promise<void> {
  const t = Date.now();
  await db.studySessions.update(id, { deletedAt: t, updatedAt: t });
}

export async function softDeleteCategory(id: number): Promise<void> {
  const t = Date.now();
  await db.studyCategories.update(id, { deletedAt: t, updatedAt: t });
}

export async function softDeleteSavedChat(id: number): Promise<void> {
  const t = Date.now();
  await db.savedChats.update(id, { deletedAt: t, updatedAt: t });
}

export async function softDeleteProblemSet(id: number): Promise<void> {
  const t = Date.now();
  await db.problemSets.update(id, { deletedAt: t, updatedAt: t });
}
